### ISSUE TITLE
现在amd平台的黑苹果在使用ps之类的软件时还会有问题吗

### ISSUE THREAD

**Issue by lioneliio** [daliansky/minisforum-HX90G-Hackintosh#1]
独显小主机诶，有点心动。

**Comment by daliansky** [comment]
<img width="1708" alt="Xnip2022-10-23_08-30-25" src="https://user-images.githubusercontent.com/18546540/197367443-26d6918a-ed5a-4611-af67-f92ac82089e4.png">
