### ISSUE TITLE
如何禁用显卡风扇参数 PP_PhmSoftPowerPlayTable

### ISSUE THREAD

**Issue by popo4u** [daliansky/minisforum-HX90G-Hackintosh#10]
如题，开启上诉后参数后风扇很吵，如何禁用掉，恢复至暖手宝版本～

**Comment by daliansky** [comment]
`config.plist`里搜索：`PP_PhmSoftPowerPlayTable`，在`PP_PhmSoftPowerPlayTable`前面添加个`#`，即：`#PP_PhmSoftPowerPlayTable`，保存即可
