### ISSUE TITLE
零刻gtr5可以安装吗

### ISSUE THREAD

**Issue by shenfu1991** [daliansky/minisforum-HX90G-Hackintosh#14]
你好，请问零刻gtr5可以安装吗，cpu是 5900hx,没有独显。
尝试用此EFI，没有安装成功。

**Comment by racso25** [comment]
I HAVE PROBLEMS WIHT REBOOT AND BOOT, WHEN I TRY TO INSTALL BY OC ON MINISFORUM HM 90

**Comment by daliansky** [comment]
抽空借台GTR5适配下，不同的机型可能都需要单独适配才能正常安装使用的
