### ISSUE TITLE
v1.1.0 在启动第二阶段 黑屏后不再亮屏

### ISSUE THREAD

**Issue by lioneliio** [daliansky/minisforum-HX90G-Hackintosh#4]
hx90g通过DP接口连接显示器
从V1.0升级为V1.1.0（仅修改三码）
启动第二阶段
黑屏后不再亮屏

附上切换为debug版OC生成的日志
[opencore-2023-03-16-114056.txt](https://github.com/daliansky/minisforum-HX90G-Hackintosh/files/10990267/opencore-2023-03-16-114056.txt)

**Comment by lioneliio** [comment]
更新 2023-03-17 版本后
黑屏问题修复
但内建USB音频没了……
只剩下 Navi 21/23 HDMI/DP Audio Controller

<img width="688" alt="Snipaste_2023-03-18_08-36-18" src="https://user-images.githubusercontent.com/38514143/226073786-cddc3038-b3ba-4e54-ba95-913ab9420694.png">

**Comment by daliansky** [comment]
已经修正，请重新下载Release 1.1.0 Fixed修正版
