### ISSUE TITLE
教程无法应用在HX99G上

### ISSUE THREAD

**Issue by lihenggui** [daliansky/minisforum-HX90G-Hackintosh#6]
HX99G使用HX80/90G系列的EFI启动失败，无法正常进入安装界面。
安装镜像为公众号提供的Ventrua 13.3, EFI从本仓库下载

以下是屏幕显示的错误信息：
![image](https://user-images.githubusercontent.com/5171312/229301462-ccbb5830-d05b-47e2-af64-333d52d67c67.png)

**Comment by daliansky** [comment]
想多了，hx99g无法安装黑苹果的，节哀

**Comment by lihenggui** [comment]
> 想多了，hx99g无法安装黑苹果的，节哀

https://github.com/Xmingbai/HX99G-Hackintosh

目前来说这个EFI是可以引导HX99G的，目前用它安装上了Ventrua 13.2.1
